routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {
   Route::resource('roles','RoleController');
   Route::resource('users','UserController');
   Route::resource('products','ProductController');
});
//Rotas Resource :: CRUD 
// -- AUTENTICACAO
Route::resource('usuarios','UsuariosController')->middleware(['auth']); 
Route::get('usuarios_pesquisar','UsuariosController@pesquisar')->name('usuarios.pesquisar')->middleware(['auth']);
Route::post('usuarios_pesquisar','UsuariosController@pesquisar')->name('usuarios.pesquisar')->middleware(['auth']);

// -- TABELA DE FATURAMENTO
Route::resource('tabelafaturamento','AgendamentoController')->middleware(['auth']);  
    //-- Especialidades
Route::resource('especialidades','EspecialidadeController')->middleware(['auth']);
Route::get('especialidades_pesquisar','EspecialidadeController@pesquisar')->name('especialidades.pesquisar')->middleware(['auth']);
Route::post('especialidades_pesquisar','EspecialidadeController@pesquisar')->name('especialidades.pesquisar')->middleware(['auth']);
Route::get('especialidades_pdf','EspecialidadeController@pdf')->name('especialidades.pdf')->middleware(['auth']);


//-- Categorias
Route::resource('categorias','CategoriaController')->middleware(['auth']);
Route::get('categorias_pesquisar','CategoriaController@pesquisar')->name('categorias.pesquisar')->middleware(['auth']);
Route::post('categorias_pesquisar','CategoriaController@pesquisar')->name('categorias.pesquisar')->middleware(['auth']);
Route::get('categorias_pdf','CategoriaController@pdf')->name('categorias.pdf')->middleware(['auth']);


   //-- Unidades
Route::resource('unidades','UnidadeController')->middleware(['auth']);
Route::get('unidades_pesquisar','UnidadeController@pesquisar')->name('unidades.pesquisar')->middleware(['auth']);
Route::post('unidades_pesquisar','UnidadeController@pesquisar')->name('unidades.pesquisar')->middleware(['auth']);
Route::get('unidades_pdf','UnidadeController@pdf')->name('unidades.pdf')->middleware(['auth']);

   //-- Convenios
Route::resource('convenios','ConvenioController')->middleware(['auth']);
Route::get('convenios_pesquisar','ConvenioController@pesquisar')->name('convenios.pesquisar')->middleware(['auth']);
Route::post('convenios_pesquisar','ConvenioController@pesquisar')->name('convenios.pesquisar')->middleware(['auth']);
Route::get('convenios_pdf','ConvenioController@pdf')->name('convenios.pdf')->middleware(['auth']);
   
   //-- Conselhos
Route::resource('conselhos','ConselhoController')->middleware(['auth']);
Route::get('conselhos_pesquisar','ConselhoController@pesquisar')->name('conselhos.pesquisar')->middleware(['auth']);
Route::post('conselhos_pesquisar','ConselhoController@pesquisar')->name('conselhos.pesquisar')->middleware(['auth']);
Route::get('conselhos_pdf','ConselhoController@pdf')->name('conselhos.pdf')->middleware(['auth']);
   
   //-- Prestadores
Route::resource('prestadores','PrestadorController')->middleware(['auth']);
Route::get('prestadores_pesquisar','PrestadorController@pesquisar')->name('prestadores.pesquisar')->middleware(['auth']);
Route::post('prestadores_pesquisar','PrestadorController@pesquisar')->name('prestadores.pesquisar')->middleware(['auth']);
Route::get('prestadores_pdf','PrestadorController@pdf')->name('prestadores.pdf')->middleware(['auth']);

   //-- Pacientes 
   Route::get('todospacientes','PacienteController@todospacientes')->middleware(['auth']);
   Route::post('novopaciente/salvar','PacienteController@novopaciente')->middleware(['auth']);
   Route::resource('pacientes','PacienteController')->middleware(['auth']);
   Route::get('pacientes_pesquisar','PacienteController@pesquisar')->name('pacientes.pesquisar')->middleware(['auth']);
   Route::get('checarpaciente/{nome?}','PacienteController@checarpaciente')->middleware(['auth']);
   Route::post('pacientes_pesquisar','PacienteController@pesquisar')->name('pacientes.pesquisar')->middleware(['auth']);
   Route::get('pacientes_pdf','PacienteController@pdf')->name('pacientes.pdf')->middleware(['auth']);
   Route::get('listarpacienteconvenios/{paciente}','PacienteController@listarpacienteconvenios')->name('listarpacienteconvenios')->middleware(['auth']);
   Route::get('removerpacienteconvenios/{paciente}/convenio/{convenio}','PacienteController@removerpacienteconvenios')->name('removerpacienteconvenios')->middleware(['auth']);
   Route::get('adicionarpacienteconvenios/{paciente}/convenio/{convenio}','PacienteController@adicionarpacienteconvenios')->name('adicionarpacienteconvenios')->middleware(['auth']);

//-- Situação Agenda
Route::resource('situacaoagenda','SituacaoAgendaController')->middleware(['auth']);
Route::get('situacaoagenda_pesquisar','SituacaoAgendaController@pesquisar')->name('situacaoagenda.pesquisar')->middleware(['auth']);
Route::post('situacaoagenda_pesquisar','SituacaoAgendaController@pesquisar')->name('situacaoagenda.pesquisar')->middleware(['auth']);
Route::get('situacaoagenda_pdf','SituacaoAgendaController@pdf')->name('situacaoagenda.pdf')->middleware(['auth']);

//-- Tipo Bloqueio
Route::resource('tipobloqueio','TipoBloqueioController')->middleware(['auth']);
Route::get('tipobloqueio_pesquisar','TipoBloqueioController@pesquisar')->name('tipobloqueio.pesquisar')->middleware(['auth']);
Route::post('tipobloqueio_pesquisar','TipoBloqueioController@pesquisar')->name('tipobloqueio.pesquisar')->middleware(['auth']);
Route::get('tipobloqueio_pdf','TipoBloqueioController@pdf')->name('tipobloqueio.pdf')->middleware(['auth']);

//-- Tipo Agenda
Route::resource('tipoagenda','TipoAgendaController')->middleware(['auth']);
Route::get('tipoagenda_pesquisar','TipoAgendaController@pesquisar')->name('tipoagenda.pesquisar')->middleware(['auth']);
Route::post('tipoagenda_pesquisar','TipoAgendaController@pesquisar')->name('tipoagenda.pesquisar')->middleware(['auth']);
Route::get('tipoagenda_pdf','TipoAgendaController@pdf')->name('tipoagenda.pdf');

//-- Tipo Atendimento
Route::resource('tipoatendimento','TipoAtendimentoController')->middleware(['auth']);
Route::get('tipoatendimento_pesquisar','TipoAtendimentoController@pesquisar')->name('tipoatendimento.pesquisar')->middleware(['auth']);
Route::post('tipoatendimento_pesquisar','TipoAtendimentoController@pesquisar')->name('tipoatendimento.pesquisar')->middleware(['auth']);
Route::get('tipoatendimento_pdf','TipoAtendimentoController@pdf')->name('tipoatendimento.pdf')->middleware(['auth']);

//-- Carater de Atendimento
Route::resource('carateratendimento','CaraterAtendimentoController')->middleware(['auth']);
Route::get('carateratendimento_pesquisar','CaraterAtendimentoController@pesquisar')->name('carateratendimento.pesquisar')->middleware(['auth']);
Route::post('carateratendimento_pesquisar','CaraterAtendimentoController@pesquisar')->name('carateratendimento.pesquisar')->middleware(['auth']);
Route::get('carateratendimento_pdf','CaraterAtendimentoController@pdf')->name('carateratendimento.pdf')->middleware(['auth']);

//-- Indicacao de Acidente
Route::resource('indicacaoacidente','IndicacaoAcidenteController')->middleware(['auth']);
Route::get('indicacaoacidente_pesquisar','IndicacaoAcidenteController@pesquisar')->name('indicacaoacidente.pesquisar')->middleware(['auth']);
Route::post('indicacaoacidente_pesquisar','IndicacaoAcidenteController@pesquisar')->name('indicacaoacidente.pesquisar')->middleware(['auth']);
Route::get('indicacaoacidente_pdf','IndicacaoAcidenteController@pdf')->name('indicacaoacidente.pdf')->middleware(['auth']);

//-- Tipo de Consulta
Route::resource('tipoconsulta','TipoConsultaController')->middleware(['auth']);
Route::get('tipoconsulta_pesquisar','TipoConsultaController@pesquisar')->name('tipoconsulta.pesquisar')->middleware(['auth']);
Route::post('tipoconsulta_pesquisar','TipoConsultaController@pesquisar')->name('tipoconsulta.pesquisar')->middleware(['auth']);
Route::get('tipoconsulta_pdf','TipoConsultaController@pdf')->name('tipoconsulta.pdf')->middleware(['auth']);

//-- FIM CRUD

//FUNCIONALIDADES 
  //-- ALOCACAO DE PRESTADORES
Route::resource('alocacao','AlocacaoController')->middleware(['auth']);
Route::post('alocacaodel', 'AlocacaoController@alocacaoDel')->name('alocacaodel')->middleware(['auth']);
Route::post('alocacaopost', 'AlocacaoController@alocacaoPost')->name('alocacaopost')->middleware(['auth']);
Route::get('listarprestadores/{prestador}/unidade/{unidade}','AlocacaoController@listarprestadores')->name('listarprestadores')->middleware(['auth']);
Route::get('listarespecialidade/{unidade}/prestador/{prestador}','AlocacaoController@listarespecialidade')->name('listarespecialidade')->middleware(['auth']);

  // -- GERAR EXPEDIENTE DO PRESTADOR
Route::resource('expediente','ExpedienteController')->middleware(['auth']); 
Route::get('listarprestador/{unidade}','ExpedienteController@listarprestador')->name('listarprestadores')->middleware(['auth']);
Route::get('listarexpediente/{unidade}/prestador/{prestador}/especialidade/{especialidade}','ExpedienteController@listarexpediente')->name('listarexpediente')->middleware(['auth']);
Route::post('expedientepost', 'ExpedienteController@expedientepost')->name('expedientepost')->middleware(['auth']);
Route::post('expedientedel', 'ExpedienteController@expedientedel')->name('expedientedel')->middleware(['auth']);
Route::get('agenda/generator/{dtinicio}/{dtfinal}/{intervalo}/{semana}','ExpedienteController@agendagenerator')->name('agendagenerator')->middleware(['auth']);

  // -- AGENDAMENTO
Route::resource('agenda','AgendamentoController')->middleware(['auth']);  
Route::get('listaragendaespecialidade/{unidade}','AgendamentoController@listaragendaespecialidade')->name('listaragendaespecialidade')->middleware(['auth']);
Route::get('listaragendaprestador/{unidade}/especialidade/{especialidade}','AgendamentoController@listaragendaprestador')->name('listaragendaprestador')->middleware(['auth']);

app/SituacaoAgenda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SituacaoAgenda extends Model
{
    protected $fillable = [
        'nome'
    ];
}

app/Http/Controllers/SituacaoAgendaController.php
<?php

namespace App\Http\Controllers;
use App\SituacaoAgenda;
use Illuminate\Http\Request;
use App\Http\Requests\SituacaoAgendaRequest;
use App\Repositories\SituacaoAgendaRepository;
use Illuminate\Database\QueryException;
class SituacaoAgendaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function pesquisar(Request $request, SituacaoAgendaRepository $repository)
    {
        $totalPage = 10;
        $situacaoagendas = $repository->pesquisar($request->nome, $totalPage);
        return view('cruds/situacaoagenda/index')->with('situacaoagendas', $situacaoagendas);
    }



    public function index(SituacaoAgendaRepository $repository)
    {
        $situacaoagendas = $repository->paginacao(10);
        return view('cruds/situacaoagenda/index')->with('situacaoagendas', $situacaoagendas);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cruds/situacaoagenda/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SituacaoAgendaRequest $request, SituacaoAgendaRepository $repository)
    {
        $repository->salvar($request);
        return redirect()
            ->action('SituacaoAgendaController@index')
            ->with('mensagem', 'Registro criado');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, SituacaoAgendaRepository $repository)
    {
        $situacaoagendas = $repository->buscarid($id);
        if(!empty($situacaoagendas)) {
            return view('cruds/situacaoagenda/edit')->with('situacaoagendas',$situacaoagendas);
        } else {
            return redirect()->action('SituacaoAgendaController@index'); 
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id, Request $request, SituacaoAgendaRepository $repository)
    {
        $repository->buscarid($id);
        $repository->update($id, $request);
        return redirect()->action('SituacaoAgendaController@index')->with('mensagem', 'O registro foi atualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, SituacaoAgendaRepository $repository)
    {
        $repository->buscarid($id);
        try {
        $repository->deletar($id);
        return redirect()->action('SituacaoAgendaController@index')->with('mensagem', 'O registro foi excluido');  
          } catch (QueryException $e) {
            return redirect()->action('SituacaoAgendaController@index')->with('warning', 'O registro pois possui relacionamentos!');
          }  
    }

    public function pdf(SituacaoAgendaRepository $repository){
        $situacaoagendas = SituacaoAgenda::all();
        return \PDF::loadView('cruds.situacaoagenda.pdf', compact('situacaoagendas'))->stream('cadastro_situacaoagenda.pdf');
    }
}

resources/views/cruds/situacaoagenda/create.blade.php
@extends('adminlte::page')

@section('title', 'AAPVR - Clínica')

@section('content_header')
    <h1>Formulário de Cadastro :: Situação Agenda</h1>
    <ol class="breadcrumb"> 
        <li><a href="/">Dashboard</a></li>
        <li><a href="">Situação Agenda</a></li>
    </ol>
@stop

@section('content')
  
@foreach($errors->all() as $error)
<div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-ban"></i> Atenção</h4>
                {{ $error }}
              </div>
@endforeach


<div class="box">
 <div class="box-header">
 <a href="{{ route('situacaoagenda.index') }}" class="btn btn-link"><span class="glyphicon glyphicon-chevron-left"></span> Voltar</a> 
 </div>

<div class="box-body">
<form action="/situacaoagenda"  method="POST">
     @csrf
<div class="form-group row">
  <div class="col-xs-5">  
      <label>* Nome</label>
      <input type="text" class="form-control" id="nome" name="nome" required>
  </div>
  </div>

  <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-save"></span> Salvar</button>
</form>
</div>
@stop

resources/views/cruds/situacaoagenda/edit.blade.php
@extends('adminlte::page')

@section('title', 'AAPVR - Clínica')

@section('content_header')
    <h1>Formulário de Edição :: Situação Agenda</h1>
    <ol class="breadcrumb"> 
        <li><a href="/">Dashboard</a></li>
        <li><a href="">Situação Agenda</a></li>
    </ol>
@stop

@section('content')
<?php 
//Somente um registro
$situacaoagendas = $situacaoagendas[0];
?>

<div class="box">
 <div class="box-header">
 <a href="{{ route('situacaoagenda.index') }}" class="btn btn-link"><span class="glyphicon glyphicon-chevron-left"></span> Voltar</a> 
 </div>

<div class="box-body">
@if(session('mensagem'))
    <div class="alert alert-success">
        <p>{{session('mensagem')}}</p>
    </div>
@endif

<form action="/situacaoagenda/<?=$situacaoagendas->id?>"  method="POST">
     @csrf
     @method('PUT')
<div class="form-group row">
  <div class="col-xs-5">  
      <label>* Nome</label>
      <input type="text" class="form-control" id="nome" name="nome" value="<?=$situacaoagendas->nome; ?>" required>
  </div>
  </div>
<button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-save"></span> Salvar</button>
</form>
</div>
<script src="{{ asset('js/mensagem.js') }}"></script>
@stop

resources/views/cruds/situacaoagenda/index.blade.php
@extends('adminlte::page')

@section('title', 'AAPVR - Clínica')

@section('content_header')
    <h1>Lista :: Situação Agenda</h1>
    <ol class="breadcrumb"> 
        <li><a href="/">Dashboard</a></li>
        <li><a href="">Situação Agenda</a></li>
    </ol>
@stop

@section('content')
<div class="box">
 <div class="box-header">
 
    <form action="{{ route('situacaoagenda.pesquisar') }}"  method="POST" class="form-inline">
     @csrf
     <input type="text" name="nome" class="form-control" placeholder="Nome">
     <button type="submit" class="btn btn-secondary"><span class="glyphicon glyphicon-search"></span> Pesquisar</button>
     <a href="{{ route('situacaoagenda.create') }}" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Novo Registro</a>
     <a href="{{ route('situacaoagenda.pdf') }}" class="btn btn-warning"><span class="glyphicon glyphicon-print"></span> Imprimir</a>
    </form>
 </div>

<div class="box-body">
@if(session('mensagem'))
<!-- Modal -->
<div class="modal modal-success fade" id="modal-success" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body">
          <p align="center"> {{session('mensagem')}}</p>
      </div>
    </div>
  </div>
</div>
@endif
@if(session('warning'))
<!-- Modal -->
<div class="modal modal-warning fade" id="modal-success" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-body">
          <p align="center"><b>Atenção!</b> <br> {{session('warning')}}</p>
      </div>
    </div>
  </div>
</div>
@endif
<!-- Fim do Modal -->

    <table class="table table-striped">
      <tr>
         <th>Nome</th>         
         <th width="100px">Ações</th>
      </tr>
    @foreach($situacaoagendas as $situacaoagenda)
        <tr>
            <td><?=$situacaoagenda['nome']?></td>
            
            <td>
                <a href="/situacaoagenda/<?=$situacaoagenda['id']?>/edit">
                   <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <a data-toggle="modal" data-target="#delete-modal<?=$situacaoagenda['id']?>" class="glyphicon glyphicon-trash">
            </td>
        </tr>
    <!-- Modal de Delete-->
<div class="modal fade" id="delete-modal<?=$situacaoagenda['id']?>" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
  <div class="modal-dialog"   role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalLabel">Excluir Item</h4>
      </div>
      <div class="modal-body">
        Deseja realmente excluir este item?
      </div>
      <div class="modal-footer">
        
      <form action="/situacaoagenda/<?=$situacaoagenda['id']?>"  method="POST">
        @csrf
        @method('DELETE')
        <button id="confirm" class="btn btn-primary" onclick="document.NameofUrForm.submit()">Sim</button>
        <button id="cancel" class="btn btn-default" data-dismiss="modal">N&atilde;o</button>
        </form>
      </div>
    </div>
  </div>
</div> <!-- /.modal -->
    @endforeach   
    </table>
    {!! $situacaoagendas->links()!!}
    </div>
</div>
<script src="{{ asset('js/mensagem.js') }}"></script>
@stop

resources/views/cruds/situacaoagenda/pdf.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Situação Agenda</title>
        <!--Custon CSS (está em /public/assets/site/css/certificate.css)-->
    </head>
    <body>

<h1>Situação Agenda</h1>
<table>
<table class="table table-striped" >
      <tr>
         <th align="left">Nome</th>
      </tr>
      <?php foreach($situacaoagendas as $situacaoagenda) { ?>
        <tr>
            <td><?=$situacaoagenda['nome']?></td>
        </tr>
      <?php } ?>   
</table>
</html>